### ISSUE TITLE
Customize navbar

### ISSUE THREAD

**Issue by MortenHofft** [gbif/hp-sprep#1]
@aserawayneasera 
Those [issue comment](https://github.com/gbif/hp-sprep/commit/982dbf81df2659929cec5b704f77d8d2384aa9c1#commitcomment-47478663)s easily gets lost. So I've created this issue for us.

> use an image instead of color for the navigation bar and footer to give it more of a Pacific feel

**Comment by MortenHofft** [comment]
It isn't something the theme supports. And neither does the Bulma library that is the foundation for the theme. So to do so you would have to write your own css.

See also https://hp-base-theme.gbif-staging.org/styling for styling options

To add a background to the navbar you could add below to your [`_sass/main.scss`](https://github.com/gbif/hp-sprep/blob/master/_sass/_main.scss) file. Since it fairly dark image, then I would change the text to white. You can do so in [`_config.yml`](https://github.com/gbif/hp-sprep/blob/master/_config.yml#L59)

```
.navbar {
  background: url('https://hp-sprep.gbif-staging.org/assets/images/Banner_1.png');
  background-size: cover;
}
```

That wouldn't change the footer and wouldn't show on mobile devices, for that you would have to add additional css.

I hope that can get you started

btw: that image has a fairly low resolution. I would suggest using an SVG instead

**Comment by MortenHofft** [comment]
As for adding icons to the menu items, then you can do so in your navigation file

You can do so using html in your markdown in your yaml 😄 
```
- text: |
    Markdown <span class="icon">  <i class="fa fa-github"></i></span>
  href: /markdown
```

You can add emojis to your text of course, but that is less flexible.
```
- text: Menu item 🌊 
  href: /menu-item-link
```

Personally I'm not a fan of either, but I'm probably just a boring dane.

**Comment by aserawayneasera** [comment]
Hi Morton,

Thank you very much for what you have suggested. I really appreciate the
help.
I agree with you on the icons which means I am probably boring too ;)

regards,

Wayne.Asera

**Comment by aserawayneasera** [comment]
Hi Morton,

Managed to make changes. I will close this issue now.

Thanks again for the help
