### ISSUE TITLE
Invasive Species Specialist Group Dataset/Checklist

### ISSUE THREAD

**Issue by aserawayneasera** [gbif/hp-sprep#11]
Hi, 
Is there a reason the datasets/checklists that was published by the Invasive Species Specialist Group below is not showing in the hosted portal? Could it be because it was hosted by GBIF Secretariat?

https://www.gbif.org/dataset/search?type=CHECKLIST&publishing_org=cdef28b1-db4e-4c58-aa71-3c5238c2d0b5&project_id=BID-PA2016-0005-REG

**Comment by MortenHofft** [comment]
The above mentioned are checklists without occurrences. The SPREP website (and the hosted portals in general) only shows occurrences records

**Comment by MortenHofft** [comment]
It sounds like what you might be interested in is the option to have a dataset search and dataset detail pages
This feature request is captured in https://github.com/gbif/hosted-portals/issues/122

It is an intersting example because it makes good sense, but - depending on what you imagine - it isn't obvious how to create a dataset search filter for it. Could you describe what you are looking for in a bit more details please?

**Comment by aserawayneasera** [comment]
At first I was hoping we could view specific checklists within the portal and possibly download the file itself if possible.
I guess we would like to view species (for example invasive species) in a specific checklists or datasets (for example published by Invasive Species Specialist Group).

Hope I am making sense

**Comment by aserawayneasera** [comment]
I guess the purpose of the hosted portal is for occurrences only.

**Comment by MortenHofft** [comment]
Focusing on occurrences only has been the declared scope for the pilot. We would like to extend that, and have started the work, but it isn't ready to use yet.

you can see an example of [dataset search](https://react-components.gbif-staging.org/?path=/story/search-datasetsearch--example) and [dataset detail](https://react-components.gbif-staging.org/?path=/story/entities-dataset-page--example) pages. 

A simple solution for now would be to simply list the dataset you believe have interest in a table and link to gbif.org to view details. You can even add a download link next to each row to download the checklists directly. Simply as a standard markdown page. It wouldn't dynamically update and do not allow for filtering etc, but it might be better than having nothing?
