### ISSUE TITLE
Same news for each language

### ISSUE THREAD

**Issue by aserawayneasera** [gbif/hp-sprep#12]
I am trying to setup each language to have the same news using one location for all posts.
At first we set up the news to have different posts locations but we decided recently that it is best to have the same news for all languages.

**Comment by MortenHofft** [comment]
So what you would like is to show the english news for all other languages as well?

**Comment by aserawayneasera** [comment]
Hi,
Same English news as well for other languages

**Comment by aserawayneasera** [comment]
I managed to do it.
Thanks anyway :)

**Comment by MortenHofft** [comment]
Nice - this is the line that makes the difference
https://github.com/gbif/hp-sprep/blob/master/_config.yml#L135

I wasn't aware you could do that actually. Apparently Liquid's `where` also work for arrays. 
https://github.com/gbif/jekyll-hp-base-theme/blob/master/_layouts/archive.html#L8

Nice to know

**Comment by aserawayneasera** [comment]
Yes definitely good to know. Thanks Morten.
