### ISSUE TITLE
use proper language codes

### ISSUE THREAD

**Issue by MortenHofft** [gbif/hp-sprep#13]
Currently the website is using non standard language codes to identify the different translations. That is fine, but isn't good in the html where browsers and search engine need to understand it. 
We should add an overwrite for the languages that use a 3 letter code

This is related to the commit
https://github.com/gbif/hp-sprep/commit/f05d0283d4b6d8172d02aa93463d4824f63e1ee1

**Comment by aserawayneasera** [comment]
Oh I see.
