### ISSUE TITLE
Menu overflow for some translations

### ISSUE THREAD

**Issue by MortenHofft** [gbif/hp-sprep#15]
The menu overflows in languages with looong words
e.g.
https://hp-sprep.gbif-staging.org/sb
On my machine I cannot change the language again.

There are 2 options, find shorter ways to say it or enable the mobile layout earlier

**Comment by MortenHofft** [comment]
see the Bulma documentation and/or https://hp-theme.gbif-staging.org/navigation

**Comment by aserawayneasera** [comment]
Unfortunately, for some languages there is no shorter way

**Comment by MortenHofft** [comment]
@aserawayneasera I took the liberty to [change the breakpoint to 1800px](https://github.com/gbif/hp-sprep/commit/f8f08716a30074f8b5d67f3a9431d9b2738fd302)
in line https://github.com/gbif/hp-sprep/blob/master/_sass/_main.scss#L1

The problem with it before was that you couldn't change the language back, nor could you see the full menu in some languages.

Let me know if you think this change was wrong and I will see if I can help find another solution

**Comment by aserawayneasera** [comment]
Thanks Morten.
I have changed the breakpoint to 1600px. Does show the full menu on top on big screens but changed to a side-nav menu when on small screens.

**Comment by MortenHofft** [comment]
I still have issues with https://hp-sprep.gbif-staging.org/sb when the breakpoint is set to 1600. I think the minimum is around 1700px

**Comment by aserawayneasera** [comment]
Ok Morten I will change it.
