### ISSUE TITLE
Opacity on the menu

### ISSUE THREAD

**Issue by MortenHofft** [gbif/hp-sprep#18]
It is quite difficult to read the drop down menus due to the opacity. I would suggest removing it or make it less transparent.

![Screenshot 2021-08-11 at 11 41 40](https://user-images.githubusercontent.com/6759267/129007523-c8777f4c-5d67-4370-89da-81ae45ea9b39.png)

**Comment by aserawayneasera** [comment]
Thanks. I have increased the opacity to 0.9 otherwise I will remove it.

**Comment by MortenHofft** [comment]
I've made a small change to the css so that the menu as a whole keeps its transparency, but the dropdown menu is pure white. It is also possible to [control the opacity of the dropdown on its own](https://github.com/gbif/hp-sprep/blob/master/_sass/_main.scss#L15) if you wish to have it, but give it less transparency than the top bar.

**Comment by aserawayneasera** [comment]
Thanks Morten
