### ISSUE TITLE
3mb png image on homepage

### ISSUE THREAD

**Issue by MortenHofft** [gbif/hp-sprep#19]
The homepage has a large png image as the header using parallax. That slows the site down quite a lot. We should find a better solution. 

We normally use a picture tag with a srcset and generate more appropriate image sizes and formats. But when parallax is enabled that isn't possible. Instead we use a css background image in those cases. That means that it is up to the content editor to scale the image and select a suitable format.

I'm not sure if we could do anything automatically, but for now the best/simplest is to change the image and/or remove the parallax effect

**Comment by MortenHofft** [comment]
I've scaled down and compressed the image as jpg.
https://github.com/gbif/hp-sprep/blob/master/assets/images/Niue-Project-Banner.jpg

It is 11 times smaller. @aserawayneasera if you are satisfied with that image quality then I suggest to change the image to use the jpg version
https://github.com/gbif/hp-sprep/blame/master/home.md#L7

**Comment by MattBlissett** [comment]
Note the WebP images would be used by most clients (they are generated as part of the build).  The size difference is even greater, the JPG-WebP is 18 times smaller than the PNG-WebP:

```
  405,504 Niue-Project-Banner.jpg
  159,744 Niue-Project-Banner.jpg.webp
4,702,208 Niue-Project-Banner.png
2,957,312 Niue-Project-Banner.png.webp
```

**Comment by aserawayneasera** [comment]
Thank you. I appreciate it. We had came across some issues with the owner on his image but yes initially the file size was 7mb we managed to compress it to 3mb. 
The current image size still looks good, I am ok with that.
So thanks again.

**Comment by MortenHofft** [comment]
I've updated the references so the new image is used instead

**Comment by aserawayneasera** [comment]
Ok thanks Morten
