### ISSUE TITLE
Divider between the home page and Feature news

### ISSUE THREAD

**Issue by aserawayneasera** [gbif/hp-sprep#2]
On the home page is it possible to put a divider between the home page and archive posts?
<img width="958" alt="divider" src="https://user-images.githubusercontent.com/27858318/109061971-94108180-7754-11eb-9229-a4fa68140597.png">

**Comment by MortenHofft** [comment]
Yes, that white area can be removed. This is just the default layout and that assumes that you will put text in there. But we can remove that.

I think the home page is a bit empty. The home page (or any other page for that matter), can be composed of several predefined blocks - and you can of course add your own.

Have you seen https://hp-base-theme.gbif-staging.org/layout/compose ?
Each block is delimited by a red line. 

If you have content that makes sense to show on the home page, then I will gladly help discussing how we could fit it in to these blocks - or it might turn out that we should add a new block type for the benefit of everyone else as well. But I guess it also depends on your plans for the site. 

I can see in the link collection that there is a lot of existing sites. Is the plan to replace any of them or is it to supplement them? As it stands this site does not have much content (which is fine, I'm just trying to understand where it is going)

**Comment by aserawayneasera** [comment]
I see. Thanks for that, I will relay what you have mentioned to others. I understand where you are coming from though. Yes the links are supplementary sites to refer the users to other existing services available to them.

**Comment by aserawayneasera** [comment]
Ok I will close this issue
