### ISSUE TITLE
Menu defaults to the root language

### ISSUE THREAD

**Issue by aserawayneasera** [gbif/hp-sprep#20]
Hi Morten,

The menu automatically changes to English when navigating to news menu and clicking on the any news article when using another language. 
Same occurs for the error page, always changes back to the English error page

**Comment by MortenHofft** [comment]
**Error page**
There is only an english "not found"-page. Pages that do not exist do not have a language I'm afraid.

**News**
It sounds like a configuration issue. The Canadian site works as I would expect. Could you look at [their code](https://github.com/gbif/hp-canadian-biodiversity) to start with?
https://hp-canadian-biodiversity.gbif-staging.org/en/news/
https://hp-canadian-biodiversity.gbif-staging.org/fr/nouvelles

**Comment by MortenHofft** [comment]
Oh I notice that the news aren't translated. If you want to show english news on the french part of the site, then you need to copy them I'm afraid.

**Comment by aserawayneasera** [comment]
Yes, the news are only in English.
Oh ok. I thought of that.
That means duplicate the news for the other 9 languages

**Comment by aserawayneasera** [comment]
thanks Morten

**Comment by MortenHofft** [comment]
Someone might have written a custom Jekyll generator that could help you to generate multiple pages from one page. But it isn't something I know anything about I'm afraid.

This plugin seem to do something related, but not exactly what you are looking for https://github.com/saclark/jekyll-multipost

If you find a good solution, then please let me know. Others might also want that (I haven't heard of any yet though)
