### ISSUE TITLE
Sticky header

### ISSUE THREAD

**Issue by MortenHofft** [gbif/hp-sprep#23]
Hi @aserawayneasera 
I notice that you have added a sticky header. Those are not without issues, so you should keep an eye on scrolling behaviour in general when using those.

On mobile for example I noticed that you have to scroll through the entire page before the menu starts scrolling.

**Comment by MortenHofft** [comment]
I believe you can fix this issue by adding below as I did in above commit (but commented out). But it isn't unlikely that other issues will appear due to the sticky header. Anchors for example tend to work badly with sticky headers.
```
.is-active {
   max-height: calc(100vh - 4.25rem);
   overflow: auto;
}
```

**Comment by aserawayneasera** [comment]
Added above as suggested.
