### ISSUE TITLE
dataset sidebar information

### ISSUE THREAD

**Issue by aserawayneasera** [gbif/hp-sprep#24]
Hi,
I maybe wrong but is the dataset sidebar window supposed to blank?
![image](https://user-images.githubusercontent.com/27858318/134981529-48ec6e8e-96f3-496f-acb8-f53ebee13b3e.png)

**Comment by MortenHofft** [comment]
no it is not. A field has been renamed in the database and I hadn't noticed so the query failed. It is fixed and deployed

**Comment by aserawayneasera** [comment]
Thanks Morten
