### ISSUE TITLE
SPREP official domain or subdomain name

### ISSUE THREAD

**Issue by aserawayneasera** [gbif/hp-sprep#8]
Hi Matt,

We have chosen the subdomain gbif-pacific.sprep.org to be the official domain name of the hosted portal.

We are planning to do a soft launch in June. 

Our IT section have updated our DNS records accordingly.

**Comment by aserawayneasera** [comment]
Hi guys,

Please note we are planning to launch the Portal on June 4th.
But for promotional and awareness purposes we need the link to be active please.
So we could push the staging the production as soon as possible please.

We will also be reaching out to GBIF soon for the launch.

Anyway, looking forward to your reply

**Comment by aserawayneasera** [comment]
Hi,

I know everyone is busy with their various projects. Apologies if I am sending a lot comments. 
It is just that we created this issue 16 days ago. And we just need a confirmation from you that the domain will be ready a week or more before June 4th 2021 (Pacific Portal Launch) please.

Apologies for the inconvenience

Thanks.

**Comment by kcopas** [comment]
Reply by email.

**Comment by aserawayneasera** [comment]
Thanks Kyle for the clarification.

**Comment by aserawayneasera** [comment]
new and revised subdomain name.

pbif.sprep.org

**Comment by MattBlissett** [comment]
Hi Wayne,

I don't see DNS entries for pbif.sprep.org.  Let me know when DNS is ready, and I can create a TLS certificate in preparation for the soft launch.

Thanks,

https://github.com/gbif/hosted-portals/blob/main/getting-started/domain-name.md#subdomains-datatecalazz-etc

**Comment by aserawayneasera** [comment]
Thanks Matt. I will follow it up.

**Comment by aserawayneasera** [comment]
Hi Matt,
We have added the DNS entries for pbif.sprep,org hopefully it is ready.

**Comment by aserawayneasera** [comment]
Just need a confirmation please, will the link pbif.sprep.org **only** be available once you get confirmation that SPREP has accepted the DPA and SLA?

**Comment by MattBlissett** [comment]
Hi Wayne,

I see you set this up using Cloudflare, though this doesn't make any difference to our configurations.

https://pbif.sprep.org now shows a holding page, and will be available once the documents are signed.

**Comment by timrobertson100** [comment]
I believe this can be closed

**Comment by aserawayneasera** [comment]
thank you everyone.
